apiVersion: v1
kind: Service
metadata:
  name: fastify-crud-api
  labels:
    app: fastify-crud-api
spec:
  type: NodePort
  selector:
    app: fastify-crud-api
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http