apiVersion: v1
kind: Service
metadata:
  name: fastify-crud-api
  labels:
    app: fastify-crud-api
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: LoadBalancer
  selector:
    app: fastify-crud-api
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http